apiVersion: batch/v1
kind: Job
metadata:
  name: taming-test
spec:
  template:
    spec:
      containers:
        - name: gpu-container
          #          image: nvcr.io/nvidia/pytorch:23.02-py3
          image: continuumio/anaconda3
          command: [ "/bin/bash","-c" ]
          args: [
            'nvidia-smi;
             git clone https://github.com/t2ance/taming-transformers.git;
             cd taming-transformers;
             conda init bash;
             source /opt/conda/etc/profile.d/conda.sh;
             conda env create -f environment.yaml;
             conda activate taming;
             python main.py --base configs/faceshq_vqgan.yaml -t True --gpus 0;
             '
          ]

          resources:
            requests:
              nvidia.com/gpu: "1"
              memory: "12G"
              cpu: "2"
            limits:
              nvidia.com/gpu: "1"
              memory: "12G"
              cpu: "2"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                      - NVIDIA-GeForce-RTX-3090
      restartPolicy: Never
