apiVersion: v1
kind: Pod
metadata:
  name: taming-test
spec:
  containers:
    - name: gpu-container
      #          image: nvcr.io/nvidia/pytorch:23.02-py3
      image: continuumio/anaconda3
      command: [ "/bin/bash","-c" ]
      args: [
        'nvidia-smi;
         git clone https://github.com/t2ance/taming-transformers.git;
         cd taming-transformers;
         conda init bash;
         source /opt/conda/etc/profile.d/conda.sh;
         conda env create -f environment.yaml;
         conda activate taming;
         jupyter lab --ip=0.0.0.0 --port=8888 --NotebookApp.token=627a7b3b --no-browser --allow-root;
         '
      ]

      resources:
        requests:
          nvidia.com/gpu: "1"
          memory: "12G"
          cpu: "2"
        limits:
          nvidia.com/gpu: "1"
          memory: "12G"
          cpu: "2"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                  - NVIDIA-GeForce-RTX-3090
  restartPolicy: Never
